= ClockDriveOS

ClockDriveOS is an application for operating motor-controlled clock-drive systems for tracking celestial objects.

Full documentation is available on https://303adastra.github.io/clockdriveos/.

== View the documentation locally

You can run your own local server to view the documentation site on a local desktop:

Note: It is recommended you run the following instructions on a Linux/Unix-like operating system. If you are on a Windows machine, consider installing https://docs.microsoft.com/en-us/windows/wsl/install-win10[Windows Subsystem for Linux].

=== Installing requirements

You will need https://git-scm.com/[git] to clone the project contents and https://www.docker.com/[docker] to run the docker image that contains the dependencies needed for building and serving the documentation.

. https://git-scm.com/downloads[git].
. https://docs.docker.com/get-docker/[docker].

=== Cloning the repo

Clone the https://github.com/303adastra/clockdriveos[flight software repo]. Don't forget to use `--recurse-submodules` flag, or else you won't pull down some of the code you need to generate a working site.

[source,bash]
----
git clone --recurse-submodules https://github.com/303adastra/clockdriveos.git
cd clockdriveos
----

Note: If you accidentally cloned without using `--recurse-submodules`, you can run `git submodule update --init --recursive` to pull down submodules needed to generate a working site.

=== Building project dependencies

Once you've cloned the repo & installed docker, run the `buildDocs.sh` script in the project root directory (Note: Linux users may need to prepend this command `sudo`). This will build a docker image, as well as install node modules, needed to locally run the `clockdriveos` Hugo webserver. Once the image is built and stored on your machine, you do not need to rerun this step. You can view all locally installed images by running `docker images`.

[source,bash]
----
./buildDocs.sh
----

=== Running local server

Run the `serve.sh` script in the project root directory (Note: Linux users may need to prepend this command `sudo`). By default, your site will be available at `+http://localhost:1313/clockdriveos+`.

[source,bash]
----
./serve.sh
----

Now that you're serving your site locally, the Hugo webserver will watch for changes to the content and automatically refresh your site.

