@startuml
left to right direction
skinparam linetype polyline
/'
skinparam linetype ortho
'/

frame "ibd [System] PID-Controlled Clock Drive [Data Flow] ]" {

  component "<b>Real Time Clock (RTC)</b>" as rtc

  rectangle "<b>PID Controller</b>" <<microcontroller>> as G {
    !include system-model/block-pid-controlled-clock-drive.puml
  }

  interface "<b>Serial Bus</b>" as serial_bus_rtc
  serial_bus_rtc . rtc : <<SPI/I2C>>
  serial_bus_rtc -- serial_read_rtc

  interface "<b>Motor Speed (PWM)</b>" as pwm
  pwm_gen --> pwm

  rectangle "<b>Motor Drive System</b>" as H {
    component "<b>motor drive</b>" as drive
    component "<b>motor</b>" as motor
    component "<b>gearbox</b>" as gearbox
    motor <- drive
    gearbox <- motor
  }

  pwm ..> drive

  interface "<b>Right Ascension (RA) Shaft</b>" as ra
  component "<b>Rotory Encoder</b>" as encoder
  interface "<b>Serial bus</b>" as serial_bus_encoder

  ra <. gearbox
  encoder <.. ra

  serial_bus_encoder - serial_read_encoder
  serial_bus_encoder .. encoder : <<SPI/I2C>>
}
@enduml
