@startuml
skinparam linetype polyline
/'
skinparam linetype ortho
'/

class RightAscensionDriver {
    == instance variables ==
    -- I/O Pins --
    rtcSclPin : int
    rtcSdaPin : int
    rotoryEncoderPinA : int
    rotoryEncoderPinB : int
    motorDriverPin : int
    -- State Variables --
    rightAscensionRef : int
    rightAscension : int
    lat : int
    lon : int
    == instance methods ==
    -- Digital Inputs --
    readRtcScl()
    readRtcSda()
    readRotoryEncoderA()
    readRotoryEncoderB()
    -- PWM Outputs --
    incrementStepper()
    decrementStepper()
    -- Operating Modes --
    calibrateNominalSpeed(duration : int)
    trackSky(nominalSpeed : int = 255, encoder : bool = false, rtc : bool = false)
}

@enduml
